name: Scrape MS Distro Sites (Manual Trigger)


on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER:     ${{ secrets.POSTGRES_USER     }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST:     ${{ secrets.POSTGRES_HOST     }}
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.13.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 psycopg2-binary

    - name: Populate Windows
      run: python3 ./scrape-microsoft.py

    - name: Populate MacOS
      run: python3 ./scrape-apple.py
